### ISSUE TITLE
path encoding error on Windows 

### ISSUE THREAD

**Issue by JoeWoo** [guard/listen#238]
windows 7 simplified Chinese version.
when I tried to listen the path "F:/文件":

``` ruby
 # coding: utf-8
require 'listen'
require 'rbconfig'
if RbConfig::CONFIG['target_os'] =~ /mswin|mingw|cygwin/i
  gem 'wdm', '>= 0.1.0'
end
path = "F:/文件"
callback = Proc.new do |modified, added, removed|
 puts "modified absolute path: #{modified}"
 puts "added absolute path: #{added}"
 puts "removed absolute path: #{removed}"
end
listener = Listen.to(path , &callback)
listener.start
sleep
```

I got an error:

```
    E, [2014-06-16T21:52:17.687923 #6324] ERROR -- : Listen::Record crashed!
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and GBK
        C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:113:in `join'
        C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:113:in `block in _fast_build'
        C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:112:in `each'
        C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:112:in `_fast_build'
        C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:67:in `block in build'
        C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:66:in `each'
        C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:66:in `build'
        C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
        C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
        C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
        C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
        C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
        C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
        C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:113:in `join': incompatible character encodings:
TF-8 and GBK (Encoding::CompatibilityError)
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:113:in `block in _fast_build'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:112:in `each'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:112:in `_fast_build'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:67:in `block in build'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:66:in `each'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:66:in `build'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_messag
'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in cre
te'
        from (celluloid):0:in `remote procedure call'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:92:in `value'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/proxies/sync_proxy.rb:33:in `method_mis
ing'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/listener.rb:81:in `block in <class:Listener>'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/fsm.rb:175:in `instance_eval'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/fsm.rb:175:in `call'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/fsm.rb:127:in `transition_with_callback
!'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/fsm.rb:95:in `transition'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/listener.rb:90:in `start'
        from ./monitor.rb:24:in `<main>'
```

but , 

``` ruby
    Dir.glob("F:/文件/*") { |file|
     puts File.dirname(file)
   }
```

works well.

Does Listen manage the path encoding by different way?

**Comment by Glutexo** [comment]
This happened to me on _macOS_ when watching a unicode path with _Guard_:

```
1] guard(main)> E, [2018-02-22T14:37:54.626052 #60457] ERROR -- : exception while processing events: incompatible character encodings: ASCII-8BIT and UTF-8 Backtrace:
 -- /usr/local/lib/ruby/gems/2.5.0/gems/guard-2.14.2/lib/guard.rb:160:in `expand_path'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/guard-2.14.2/lib/guard.rb:160:in `expand_path'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/guard-2.14.2/lib/guard.rb:160:in `block in _guardfile_deprecated_check'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/guard-2.14.2/lib/guard.rb:159:in `each'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/guard-2.14.2/lib/guard.rb:159:in `detect'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/guard-2.14.2/lib/guard.rb:159:in `_guardfile_deprecated_check'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/guard-2.14.2/lib/guard.rb:121:in `block in _listener_callback'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/config.rb:23:in `call'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:115:in `_process_changes'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:19:in `block in loop_for'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop_for'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
 -- /usr/local/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
```

Maybe it is the same error? My watched path is _/Users/Glutexo/Vývoj/sample_app_. The _ý_ is the culprit. When moved to _/Users/Glutexo/Development/sample_app_, the bug disappeared.

**Comment by ColinDKelley** [comment]
If this bug persists, it looks like it would need to be fixed in `guard`, not `listen`, since it's `guard`'s callback that tried the comparisons between incompatible character sets. So I'm closing this out here.
