### ISSUE TITLE
listener.stop fails with undefined method `alive?' for nil:NilClass if called before started

### ISSUE THREAD

**Issue by ColinDKelley** [guard/listen#513]
## Current State

If a listener hasn't been started yet, a call to `stop` will raise an exception:

```
listener = Listen.to(path) do { ... }
listener.stop
NoMethodError:
       undefined method `alive?' for nil:NilClass
     # /usr/local/bundle/gems/listen-3.3.0/lib/listen/event/loop.rb:70:in `stop'
     # /usr/local/bundle/gems/listen-3.3.0/lib/listen/listener.rb:82:in `block in <class:Listener>'
     # /usr/local/bundle/gems/listen-3.3.0/lib/listen/fsm.rb:121:in `instance_eval'
     # /usr/local/bundle/gems/listen-3.3.0/lib/listen/fsm.rb:121:in `call'
     # /usr/local/bundle/gems/listen-3.3.0/lib/listen/fsm.rb:102:in `transition_with_callbacks!'
     # /usr/local/bundle/gems/listen-3.3.0/lib/listen/fsm.rb:69:in `transition'
     # /usr/local/bundle/gems/listen-3.3.0/lib/listen/listener.rb:101:in `stop'
```

## Desired State

The `stop` method should always succeed--even when not started.

## Steps to Reproduce

Call `stop` before starting:
```
listener = Listen.to(path) do { ... }
listener.stop
```

**Comment by ColinDKelley** [comment]
Fixed by https://github.com/guard/listen/pull/514
